# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: toki-pona-parser
version: '0.0.0'
github: "baujmi/toki-pona-parser"
license: MIT
author: "Faith Alderson"
maintainer: "Faith Alderson"
# synopsis: A new Haskeleton package.
# description: toki-pona-parser is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - trifecta
  - lens
  - text
  - show-prettyprint
  - ansi-wl-pprint
  source-dirs: library

executables:
  toki-pona-parser:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - toki-pona-parser
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  toki-pona-parser-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - toki-pona-parser
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  toki-pona-parser-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - toki-pona-parser
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
